### ISSUE TITLE
Automatic download will delete my original other environment,

### ISSUE THREAD

**Issue by 15704080** [tin2tin/Generative_AI#16]
Read prefs: C:\Users\KATMASTE\AppData\Roaming\Blender Foundation\Blender\3.4\config\userpref.blend
addon_utils.disable: Generative_AI-main not disabled
已安装模块 (Generative_AI-main)，从 'C:\\Users\\KATMASTE\\Downloads\\Generative_AI-main.zip' 到 'F:\\blender\\C\\addons'
Ensuring: pip
Looking in links: c:\Users\KATMASTE\AppData\Local\Temp\tmpe9app59k
Requirement already satisfied: setuptools in f:\blender\3.4\python\lib\site-packages (63.2.0)
Requirement already satisfied: pip in f:\blender\3.4\python\lib\site-packages (22.2.2)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: pip in f:\blender\3.4\python\lib\site-packages (22.2.2)
Collecting pip
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/08/e3/57d4c24a050aa0bcca46b2920bff40847db79535dc78141eb83581a52eb8/pip-23.1.2-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.2.2
    Uninstalling pip-22.2.2:
      Successfully uninstalled pip-22.2.2
  WARNING: The scripts pip.exe, pip3.10.exe and pip3.exe are installed in 'F:\blender\3.4\python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-23.1.2
Installing: torch module
Looking in indexes: https://download.pytorch.org/whl/cu118
Collecting torch
  Using cached https://download.pytorch.org/whl/cu118/torch-2.0.1%2Bcu118-cp310-cp310-win_amd64.whl (2619.1 MB)
Collecting filelock (from torch)
  Using cached https://download.pytorch.org/whl/filelock-3.9.0-py3-none-any.whl (9.7 kB)
Collecting typing-extensions (from torch)
  Using cached https://download.pytorch.org/whl/typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting sympy (from torch)
  Using cached https://download.pytorch.org/whl/sympy-1.11.1-py3-none-any.whl (6.5 MB)
Collecting networkx (from torch)
  Using cached https://download.pytorch.org/whl/networkx-3.0-py3-none-any.whl (2.0 MB)
Collecting jinja2 (from torch)
  Using cached https://download.pytorch.org/whl/Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch)
  Using cached https://download.pytorch.org/whl/MarkupSafe-2.1.2-cp310-cp310-win_amd64.whl (16 kB)
Collecting mpmath>=0.19 (from sympy->torch)
  Using cached https://download.pytorch.org/whl/mpmath-1.2.1-py3-none-any.whl (532 kB)
Installing collected packages: mpmath, typing-extensions, sympy, networkx, MarkupSafe, filelock, jinja2, torch
Successfully installed MarkupSafe-2.1.2 filelock-3.9.0 jinja2-3.1.2 mpmath-1.2.1 networkx-3.0 sympy-1.11.1 torch-2.0.1+cu118 typing-extensions-4.4.0
Looking in indexes: https://download.pytorch.org/whl/cu118
Collecting torchvision
  Using cached https://download.pytorch.org/whl/cu118/torchvision-0.15.2%2Bcu118-cp310-cp310-win_amd64.whl (4.9 MB)
Requirement already satisfied: numpy in f:\blender\3.4\python\lib\site-packages (from torchvision) (1.22.0)
Requirement already satisfied: requests in f:\blender\3.4\python\lib\site-packages (from torchvision) (2.27.1)
Requirement already satisfied: torch==2.0.1 in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from torchvision) (2.0.1+cu118)
Collecting pillow!=8.3.*,>=5.3.0 (from torchvision)
  Using cached https://download.pytorch.org/whl/Pillow-9.3.0-cp310-cp310-win_amd64.whl (2.5 MB)
Requirement already satisfied: filelock in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from torch==2.0.1->torchvision) (3.9.0)
Requirement already satisfied: typing-extensions in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from torch==2.0.1->torchvision) (4.4.0)
Requirement already satisfied: sympy in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from torch==2.0.1->torchvision) (1.11.1)
Requirement already satisfied: networkx in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from torch==2.0.1->torchvision) (3.0)
Requirement already satisfied: jinja2 in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from torch==2.0.1->torchvision) (3.1.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in f:\blender\3.4\python\lib\site-packages (from requests->torchvision) (1.26.8)
Requirement already satisfied: certifi>=2017.4.17 in f:\blender\3.4\python\lib\site-packages (from requests->torchvision) (2021.10.8)
Requirement already satisfied: charset_normalizer~=2.0.0 in f:\blender\3.4\python\lib\site-packages (from requests->torchvision) (2.0.10)
Requirement already satisfied: idna<4,>=2.5 in f:\blender\3.4\python\lib\site-packages (from requests->torchvision) (3.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from jinja2->torch==2.0.1->torchvision) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from sympy->torch==2.0.1->torchvision) (1.2.1)
Installing collected packages: pillow, torchvision
Successfully installed pillow-9.3.0 torchvision-0.15.2+cu118
Looking in indexes: https://download.pytorch.org/whl/cu118
Collecting torchaudio
  Using cached https://download.pytorch.org/whl/cu118/torchaudio-2.0.2%2Bcu118-cp310-cp310-win_amd64.whl (2.5 MB)
Requirement already satisfied: torch==2.0.1 in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from torchaudio) (2.0.1+cu118)
Requirement already satisfied: filelock in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from torch==2.0.1->torchaudio) (3.9.0)
Requirement already satisfied: typing-extensions in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from torch==2.0.1->torchaudio) (4.4.0)
Requirement already satisfied: sympy in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from torch==2.0.1->torchaudio) (1.11.1)
Requirement already satisfied: networkx in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from torch==2.0.1->torchaudio) (3.0)
Requirement already satisfied: jinja2 in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from torch==2.0.1->torchaudio) (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from jinja2->torch==2.0.1->torchaudio) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from sympy->torch==2.0.1->torchaudio) (1.2.1)
Installing collected packages: torchaudio
Successfully installed torchaudio-2.0.2+cu118
Installing: soundfile module
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting PySoundFile
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/9d/8e/30d9f80802e8ea2c5b96db2f320fdb147e25a84fd74caa251b57bedeeb33/PySoundFile-0.9.0.post1-py2.py3.cp26.cp27.cp32.cp33.cp34.cp35.cp36.pp27.pp32.pp33-none-win_amd64.whl (671 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 671.8/671.8 kB 476.0 kB/s eta 0:00:00
Collecting cffi>=0.6 (from PySoundFile)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/0e/e2/a23af3d81838c577571da4ff01b799b0c2bbde24bd924d97e228febae810/cffi-1.15.1-cp310-cp310-win_amd64.whl (179 kB)
Collecting pycparser (from cffi>=0.6->PySoundFile)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/62/d5/5f610ebe421e85889f2e55e33b7f9a6795bd982198517d912eb1c76e1a53/pycparser-2.21-py2.py3-none-any.whl (118 kB)
Installing collected packages: pycparser, cffi, PySoundFile
Successfully installed PySoundFile-0.9.0.post1 cffi-1.15.1 pycparser-2.21
Installing: diffusers module
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting diffusers
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/4f/77/fbc170e78132944cdf5ccbb3d236af52d7b0958ad5339091523b021e91ea/diffusers-0.16.1-py3-none-any.whl (934 kB)
Requirement already satisfied: Pillow in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from diffusers) (9.3.0)
Requirement already satisfied: filelock in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from diffusers) (3.9.0)
Collecting huggingface-hub>=0.13.2 (from diffusers)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/58/34/c57b951aecd0248845932c1cfc15721237c50e463f26b0536673bcb76f4f/huggingface_hub-0.14.1-py3-none-any.whl (224 kB)
Collecting importlib-metadata (from diffusers)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/30/bb/bf2944b8b88c65b797acc2c6a2cb0fb817f7364debf0675792e034013858/importlib_metadata-6.6.0-py3-none-any.whl (22 kB)
Requirement already satisfied: numpy in f:\blender\3.4\python\lib\site-packages (from diffusers) (1.22.0)
Collecting regex!=2019.12.17 (from diffusers)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/a8/e1/581b12525a47073e38517aeb4621b4e189ac949158c3bf3f2a9c87fd4910/regex-2023.5.5-cp310-cp310-win_amd64.whl (267 kB)
Requirement already satisfied: requests in f:\blender\3.4\python\lib\site-packages (from diffusers) (2.27.1)
Collecting fsspec (from huggingface-hub>=0.13.2->diffusers)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ec/4e/397b234a369df06ec782666fcdf9791d125ca6de48729814b381af8c6c03/fsspec-2023.5.0-py3-none-any.whl (160 kB)
Collecting tqdm>=4.42.1 (from huggingface-hub>=0.13.2->diffusers)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/e6/02/a2cff6306177ae6bc73bc0665065de51dfb3b9db7373e122e2735faf0d97/tqdm-4.65.0-py3-none-any.whl (77 kB)
Collecting pyyaml>=5.1 (from huggingface-hub>=0.13.2->diffusers)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b7/09/2f6f4851bbca08642fef087bade095edc3c47f28d1e7bff6b20de5262a77/PyYAML-6.0-cp310-cp310-win_amd64.whl (151 kB)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from huggingface-hub>=0.13.2->diffusers) (4.4.0)
Collecting packaging>=20.9 (from huggingface-hub>=0.13.2->diffusers)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ab/c3/57f0601a2d4fe15de7a553c00adbc901425661bf048f2a22dfc500caf121/packaging-23.1-py3-none-any.whl (48 kB)
Collecting zipp>=0.5 (from importlib-metadata->diffusers)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/5b/fa/c9e82bbe1af6266adf08afb563905eb87cab83fde00a0a08963510621047/zipp-3.15.0-py3-none-any.whl (6.8 kB)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in f:\blender\3.4\python\lib\site-packages (from requests->diffusers) (1.26.8)
Requirement already satisfied: certifi>=2017.4.17 in f:\blender\3.4\python\lib\site-packages (from requests->diffusers) (2021.10.8)
Requirement already satisfied: charset_normalizer~=2.0.0 in f:\blender\3.4\python\lib\site-packages (from requests->diffusers) (2.0.10)
Requirement already satisfied: idna<4,>=2.5 in f:\blender\3.4\python\lib\site-packages (from requests->diffusers) (3.3)
Collecting colorama (from tqdm>=4.42.1->huggingface-hub>=0.13.2->diffusers)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/d1/d6/3965ed04c63042e047cb6a3e6ed1a63a35087b6a609aa3a15ed8ac56c221/colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Installing collected packages: zipp, regex, pyyaml, packaging, fsspec, colorama, tqdm, importlib-metadata, huggingface-hub, diffusers
Successfully installed colorama-0.4.6 diffusers-0.16.1 fsspec-2023.5.0 huggingface-hub-0.14.1 importlib-metadata-6.6.0 packaging-23.1 pyyaml-6.0 regex-2023.5.5 tqdm-4.65.0 zipp-3.15.0
Installing: accelerate module
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting accelerate
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/fe/03/08a2f414de4ce11fae93a079e4184a7397f34d956c894359ed801b89dae0/accelerate-0.19.0-py3-none-any.whl (219 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 219.1/219.1 kB 607.2 kB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17 in f:\blender\3.4\python\lib\site-packages (from accelerate) (1.22.0)
Requirement already satisfied: packaging>=20.0 in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from accelerate) (23.1)
Collecting psutil (from accelerate)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/86/f3/23e4e4e7ec7855d506ed928756b04735c246b14d9f778ed7ffaae18d8043/psutil-5.9.5-cp36-abi3-win_amd64.whl (255 kB)
Requirement already satisfied: pyyaml in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from accelerate) (6.0)
Requirement already satisfied: torch>=1.6.0 in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from accelerate) (2.0.1+cu118)
Requirement already satisfied: filelock in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from torch>=1.6.0->accelerate) (3.9.0)
Requirement already satisfied: typing-extensions in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from torch>=1.6.0->accelerate) (4.4.0)
Requirement already satisfied: sympy in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from torch>=1.6.0->accelerate) (1.11.1)
Requirement already satisfied: networkx in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from torch>=1.6.0->accelerate) (3.0)
Requirement already satisfied: jinja2 in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from torch>=1.6.0->accelerate) (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from jinja2->torch>=1.6.0->accelerate) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from sympy->torch>=1.6.0->accelerate) (1.2.1)
Installing collected packages: psutil, accelerate
Successfully installed accelerate-0.19.0 psutil-5.9.5
Installing: transformers module
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting transformers
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/e8/b5/ddb16f9de207e6571ab7cc5db0cc538fa2d6d91cf024565496462af4c1ce/transformers-4.29.1-py3-none-any.whl (7.1 MB)
Requirement already satisfied: filelock in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from transformers) (3.9.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.14.1 in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from transformers) (0.14.1)
Requirement already satisfied: numpy>=1.17 in f:\blender\3.4\python\lib\site-packages (from transformers) (1.22.0)
Requirement already satisfied: packaging>=20.0 in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from transformers) (23.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from transformers) (6.0)
Requirement already satisfied: regex!=2019.12.17 in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from transformers) (2023.5.5)
Requirement already satisfied: requests in f:\blender\3.4\python\lib\site-packages (from transformers) (2.27.1)
Collecting tokenizers!=0.11.3,<0.14,>=0.11.1 (from transformers)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/3d/e7/ea70a1a0cd9ad5b4786365edd4042c30037bc4e67ae09c53cd62c6c1b89f/tokenizers-0.13.3-cp310-cp310-win_amd64.whl (3.5 MB)
Requirement already satisfied: tqdm>=4.27 in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from transformers) (4.65.0)
Requirement already satisfied: fsspec in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from huggingface-hub<1.0,>=0.14.1->transformers) (2023.5.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from huggingface-hub<1.0,>=0.14.1->transformers) (4.4.0)
Requirement already satisfied: colorama in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in f:\blender\3.4\python\lib\site-packages (from requests->transformers) (1.26.8)
Requirement already satisfied: certifi>=2017.4.17 in f:\blender\3.4\python\lib\site-packages (from requests->transformers) (2021.10.8)
Requirement already satisfied: charset_normalizer~=2.0.0 in f:\blender\3.4\python\lib\site-packages (from requests->transformers) (2.0.10)
Requirement already satisfied: idna<4,>=2.5 in f:\blender\3.4\python\lib\site-packages (from requests->transformers) (3.3)
Installing collected packages: tokenizers, transformers
Successfully installed tokenizers-0.13.3 transformers-4.29.1
Installing: sentencepiece module
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting sentencepiece
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/21/8c/54bd0e155ec945cd8bcf387c25b2d337b345f2e56939336d71183dc1804f/sentencepiece-0.1.99-cp310-cp310-win_amd64.whl (977 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 977.5/977.5 kB 429.9 kB/s eta 0:00:00
Installing collected packages: sentencepiece
Successfully installed sentencepiece-0.1.99
Installing: safetensors module
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting safetensors
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/39/7b/c785536dc1307214f4def6e6ddd772c9a76d3b5798f2961644fac10f373d/safetensors-0.3.1-cp310-cp310-win_amd64.whl (263 kB)
Installing collected packages: safetensors
Successfully installed safetensors-0.3.1
Installing: cv2 module
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting opencv_python
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/36/98/fab8d982e2e2b57bdebcad64c7e5b5a14ac91c657cac509b9cf3fbea49d2/opencv_python-4.7.0.72-cp37-abi3-win_amd64.whl (38.2 MB)
Requirement already satisfied: numpy>=1.21.2 in f:\blender\3.4\python\lib\site-packages (from opencv_python) (1.22.0)
Installing collected packages: opencv_python
Successfully installed opencv_python-4.7.0.72
Installing: scipy module
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting scipy
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ec/e3/b06ac3738bf365e89710205a471abe7dceec672a51c244b469bc5d1291c7/scipy-1.10.1-cp310-cp310-win_amd64.whl (42.5 MB)
Requirement already satisfied: numpy<1.27.0,>=1.19.5 in f:\blender\3.4\python\lib\site-packages (from scipy) (1.22.0)
Installing collected packages: scipy
Successfully installed scipy-1.10.1
Installing: xformers module
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting xformers
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/c5/f1/af0acb6c8e8f04989831cc1f1ca95015c2f90e37cf17ffc9b2fa23dd073e/xformers-0.0.19-cp310-cp310-win_amd64.whl (96.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.7/96.7 MB 292.5 kB/s eta 0:00:00
Requirement already satisfied: numpy in f:\blender\3.4\python\lib\site-packages (from xformers) (1.22.0)
Collecting pyre-extensions==0.0.29 (from xformers)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ce/96/2fd3042ad8b21278f22b7de116b1489e286c445f07c309c85221db86f120/pyre_extensions-0.0.29-py3-none-any.whl (12 kB)
Collecting torch==2.0.0 (from xformers)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/87/e2/62dbdfc85d3b8f771bc4b1a979ee6a157dbaa8928981dabbf45afc6d13dc/torch-2.0.0-cp310-cp310-win_amd64.whl (172.3 MB)
Collecting typing-inspect (from pyre-extensions==0.0.29->xformers)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/be/01/59b743dca816c4b6ca891b9e0f84d20513cd61bdbbaa8615de8f5aab68c1/typing_inspect-0.8.0-py3-none-any.whl (8.7 kB)
Requirement already satisfied: typing-extensions in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from pyre-extensions==0.0.29->xformers) (4.4.0)
Requirement already satisfied: filelock in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from torch==2.0.0->xformers) (3.9.0)
Requirement already satisfied: sympy in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from torch==2.0.0->xformers) (1.11.1)
Requirement already satisfied: networkx in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from torch==2.0.0->xformers) (3.0)
Requirement already satisfied: jinja2 in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from torch==2.0.0->xformers) (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from jinja2->torch==2.0.0->xformers) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in c:\users\katmaste\appdata\roaming\python\python310\site-packages (from sympy->torch==2.0.0->xformers) (1.2.1)
Collecting mypy-extensions>=0.3.0 (from typing-inspect->pyre-extensions==0.0.29->xformers)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/2a/e2/5d3f6ada4297caebe1a2add3b126fe800c96f56dbe5d1988a2cbe0b267aa/mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Installing collected packages: mypy-extensions, typing-inspect, torch, pyre-extensions, xformers
  Attempting uninstall: torch
    Found existing installation: torch 2.0.1+cu118
    Uninstalling torch-2.0.1+cu118:
      Successfully uninstalled torch-2.0.1+cu118
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.0.2+cu118 requires torch==2.0.1, but you have torch 2.0.0 which is incompatible.
torchvision 0.15.2+cu118 requires torch==2.0.1, but you have torch 2.0.0 which is incompatible.
Successfully installed mypy-extensions-1.0.0 pyre-extensions-0.0.29 torch-2.0.0 typing-inspect-0.8.0 xformers-0.0.19
Installing: bark module
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting git+https://github.com/suno-ai/bark.git
  Cloning https://github.com/suno-ai/bark.git to c:\users\katmaste\appdata\local\temp\pip-req-build-t5t9codz
  Running command git clone --filter=blob:none --quiet https://github.com/suno-ai/bark.git 'C:\Users\KATMASTE\AppData\Local\Temp\pip-req-build-t5t9codz'
  error: RPC failed; curl 28 Recv failure: Connection was reset
  fatal: expected flush after ref listing
  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet https://github.com/suno-ai/bark.git 'C:\Users\KATMASTE\AppData\Local\Temp\pip-req-build-t5t9codz' did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/suno-ai/bark.git 'C:\Users\KATMASTE\AppData\Local\Temp\pip-req-build-t5t9codz' did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "F:\blender\C\addons\Generative_AI-main\__init__.py", line 193, in import_module
    exec("import " + module)
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'bark'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\blender\C\addons\Generative_AI-main\__init__.py", line 415, in execute
    install_modules(self)
  File "F:\blender\C\addons\Generative_AI-main\__init__.py", line 296, in install_modules
    import_module(self, "bark", "git+https://github.com/suno-ai/bark.git")
  File "F:\blender\C\addons\Generative_AI-main\__init__.py", line 201, in import_module
    subprocess.check_call(
  File "F:\blender\3.4\python\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['F:\\blender\\3.4\\python\\bin\\python.exe', '-m', 'pip', 'install', 'git+https://github.com/suno-ai/bark.git', '--no-warn-script-location', '--user']' returned non-zero exit status 1.
淇℃伅: Installing: torch module.
淇℃伅: Installing: soundfile module.
淇℃伅: Installing: diffusers module.
淇℃伅: Installing: accelerate module.
淇℃伅: Installing: transformers module.
淇℃伅: Installing: sentencepiece module.
淇℃伅: Installing: safetensors module.
淇℃伅: Installing: cv2 module.
淇℃伅: Installing: scipy module.
淇℃伅: Installing: xformers module.
淇℃伅: Installing: bark module.
閿欒: Python: Traceback (most recent call last):
  File "F:\blender\C\addons\Generative_AI-main\__init__.py", line 193, in import_module
    exec("import " + module)
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'bark'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\blender\C\addons\Generative_AI-main\__init__.py", line 415, in execute
    install_modules(self)
  File "F:\blender\C\addons\Generative_AI-main\__init__.py", line 296, in install_modules
    import_module(self, "bark", "git+https://github.com/suno-ai/bark.git")
  File "F:\blender\C\addons\Generative_AI-main\__init__.py", line 201, in import_module
    subprocess.check_call(
  File "F:\blender\3.4\python\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['F:\\blender\\3.4\\python\\bin\\python.exe', '-m', 'pip', 'install', 'git+https://github.com/suno-ai/bark.git', '--no-warn-script-location', '--user']' returned non-zero exit status 1.

**Comment by tin2tin** [comment]
Did you remember to install: https://git-scm.com/downloads first, as described in the installation instructions? Could be the reason to the Bark not installing correctly. 

About your headline: "Automatic download will delete my original other environment,", maybe you can explain in a little more detail what your problem here is? It is installing all python modules into your Blender installed python, so it shouldn't affect your main python installation?

**Comment by tin2tin** [comment]
I don't understand the problem from the description. I'm closing the report for now. Feel free to reopen it if it persists or some additional info can be added.
