### ISSUE TITLE
prompt_emds is undefined

### ISSUE THREAD

**Issue by anteaterho** [tin2tin/Generative_AI#18]
Hello.

When I try to use the "DeepFloyd/IF-I-M-v1.0" model to generate images, I get a name error saying prompt_emds is undefined.
How can I solve this?

![genai_error_00](https://github.com/tin2tin/Generative_AI/assets/773412/9537ce9c-15e3-4eb2-bd4a-2f9b527fdddb)

When I open the __init__.py file in Visual Studio code, it also says that prompt_embeds and negative_embeds are undefined.

![genai_error](https://github.com/tin2tin/Generative_AI/assets/773412/73b4bded-c06b-4183-ab05-e0e00ced7113)

**Comment by tin2tin** [comment]
This is a simple fix. 
=prompt_embeds should be renamed to =prompt
=negative_embeds should be renamed to =negative_prompt

As I do not have the hardware to run Deep Floyd, I have not been able to run this code myself. Please let me know how it goes after this fix. 

I'll update the add-on script accordingly.

**Comment by anteaterho** [comment]
Ah, Thanks, fortunatelymy laptop's GPU has 16GB of VRAM.

As you said, I modified the code as shown below.
![image](https://github.com/tin2tin/Generative_AI/assets/773412/963b829f-cd22-4fbd-8e3c-c428acf93c60)

But this time, I got an AttributeError as shown below.
![image](https://github.com/tin2tin/Generative_AI/assets/773412/70bc6956-222b-4dc0-a075-8b9efa08d6f3)

**Comment by tin2tin** [comment]
If you changed everything which is highlighted in your screenshot, it'll cause errors. Try redownloading the add-on from Github.

**Comment by anteaterho** [comment]
I think you're using the diffuser's default example.

https://github.com/deep-floyd/IF

So instead of fixing prompts_embeds to prompt and negative_embeds to negative_prompt in the arguments of the stage_1 function on line 1062, I added the code below.

prompt_embeds, negative_embeds = stage_1.encode_prompt(prompt)


![image](https://github.com/tin2tin/Generative_AI/assets/773412/1c425ae2-eacc-45b6-869e-5a0eac3420da)

Then I got an error for image.save(out_path) like below. I think the image is a list, so there is no save function.

**Comment by tin2tin** [comment]
Cool. So far so good. It's properly better you have a stab at it. Yes, I used the example(at the time). Maybe something has changed in the saving code?

You're more than welcome to submit a patch if you get it working. :-)

**Comment by tin2tin** [comment]
@anteaterho Maybe `image = image[0]` will do the trick?

![image](https://github.com/tin2tin/Generative_AI/assets/1322593/08e3c7e8-33c2-4219-8cc3-c272deea78d8)

**Comment by anteaterho** [comment]
Oh Thanks. It works!!

![image](https://github.com/tin2tin/Generative_AI/assets/773412/21cdf5fd-2daa-4e89-839e-f24796aa43a0)

I didn't quite understand your trick, can you explain it to me?

**Comment by tin2tin** [comment]
Wow, cool! 

The error what that it couldn't save a list, and image was a list, where image[0] was saved, meaning the first entry of that list, so, we just needed to add that to the image variable. 

I'm a bit puzzled about this one, because it doesn't seem to define the negative prompt: 
`prompt_embeds, negative_embeds = stage_1.encode_prompt(prompt)`

How does it work if you give it a prompt ex. "a sign saying: hello"?

(I see the watermark, so it must be Deep Floyd working right there!)

**Comment by anteaterho** [comment]
I see, I got it, thanks for your explanation.

I'm also curious about the negative prompt in DeepFloyd IF. I'll have to look for some documentation on that.

I put the prompt in exactly like the example you gave, and it works. So cool!!

![image](https://github.com/tin2tin/Generative_AI/assets/773412/466a3522-e163-45df-9201-10d23bb218d5)

**Comment by anteaterho** [comment]
This is the result of typing an example from Deep Floyd IF's homepage into the prompt.

prompt : a photo of a frog reading the newspaper named "toaday" writen on it. there is a frog printed on the newspaper too.

![image](https://github.com/tin2tin/Generative_AI/assets/773412/97521afb-ebdd-436d-b9f4-75b54ca6df12)

**Comment by anteaterho** [comment]
For starters, neither method throws an error.

And according to the documentation below, it's clear that the encode_prompt function has a negative_prompt argument.
https://huggingface.co/docs/diffusers/main/en/api/pipelines/if
![image](https://github.com/tin2tin/Generative_AI/assets/773412/d04ced72-4138-4de1-8d1c-b304960930ad)


However, it's hard to see any noticeable change when adding a negative prompt.

Do you have any negative prompts you'd like to test?

**Comment by tin2tin** [comment]
I've got it running on my 6 GB VRAM. It's not very fast, but it works.

**Comment by anteaterho** [comment]
Oh, I'm glad to hear you can run it.

I don't know if this is correct, but I tried generating the image with different negative prompts as shown below.

No negative prompts

![image](https://github.com/tin2tin/Generative_AI/assets/773412/47277123-a0a0-4e2b-9a95-c60f0b98eefe)

At the negative prompt, writed Dark Fur.

![image](https://github.com/tin2tin/Generative_AI/assets/773412/9077eb37-9a8f-4fae-8f0b-9d63fef15265)

I wish I had fixed the random seed, but the image would have been generated differently with a negative prompt if I had fixed the random seed.

**Comment by tin2tin** [comment]
In order to get it to run on 6 GB VRAM I had to add one line which may cause a slower procession on your setup, but if you uncomment the first line and comment the 2. it should work as it does now for you. 
![image](https://github.com/tin2tin/Generative_AI/assets/1322593/ad765c8b-a8e7-4a92-96da-3e0d73085391)

If you have time, could you check how much slower it'll be for you with the slower processing? 

BTW. the X and Y do not have any effect as it is, but part of the process is upscaling, so it may not work with custom resolutions. I'll have to check.

**Comment by anteaterho** [comment]
6 GB VRAM code
When I created an image with the addon with the 6GB Vram code you added, it took about 1 minute and 45 seconds.

![image](https://github.com/tin2tin/Generative_AI/assets/773412/281990d7-adec-4980-9c95-7ce72c166be1)

None 6 GB VRAM code
Below is the result of commenting out the code you added for 6GB of VRAM.
![image](https://github.com/tin2tin/Generative_AI/assets/773412/b400dbac-09d4-401c-808e-45e9c2d87950)

The generated image and prompt is shown below.
![image](https://github.com/tin2tin/Generative_AI/assets/773412/692ef339-e45c-43b4-9ec3-61c8b004fb2c)

The x,y values don't seem to work as you say.

**Comment by tin2tin** [comment]
Thank you! The trouble is that I can't find a unified way to check the amount of VRAM cross-platform. And I have no access nor knowledge of dealing with Mac and Linux.

The X and Y values can properly just be added commands, but I need a bit of time to test that.

**Comment by tin2tin** [comment]
I think we have solved this now. Thank you for your help.
