### ISSUE TITLE
Blender Closes after generating a video 

### ISSUE THREAD

**Issue by eliecer696** [tin2tin/Generative_AI#20]
blender just close after the last step is complete all i get in the console is this 
Starting work on proxy: C:\Users\elio\AppData\Roaming\Blender Foundation\Blender\3.5\datafiles\Generator AI\BL_proxy\tmpfar3ea_c.mp4\proxy_100_part.avi
Starting work on index: C:\Users\elio\AppData\Roaming\Blender Foundation\Blender\3.5\datafiles\Generator AI\BL_proxy\tmpfar3ea_c.mp4\record_run.blen_tc
Starting work on index: C:\Users\elio\AppData\Roaming\Blender Foundation\Blender\3.5\datafiles\Generator AI\BL_proxy\tmpfar3ea_c.mp4\free_run.blen_tc
Starting work on index: C:\Users\elio\AppData\Roaming\Blender Foundation\Blender\3.5\datafiles\Generator AI\BL_proxy\tmpfar3ea_c.mp4\interp_free_run.blen_tc
Starting work on index: C:\Users\elio\AppData\Roaming\Blender Foundation\Blender\3.5\datafiles\Generator AI\BL_proxy\tmpfar3ea_c.mp4\record_run_no_gaps.blen_tc
Starting work on proxy: C:\Users\elio\AppData\Roaming\Blender Foundation\Blender\3.5\datafiles\Generator AI\BL_proxy\tmpfar3ea_c.mp4\proxy_100_part.avi
Starting work on index: C:\Users\elio\AppData\Roaming\Blender Foundation\Blender\3.5\datafiles\Generator AI\BL_proxy\tmpfar3ea_c.mp4\record_run.blen_tc
Starting work on index: C:\Users\elio\AppData\Roaming\Blender Foundation\Blender\3.5\datafiles\Generator AI\BL_proxy\tmpfar3ea_c.mp4\free_run.blen_tc
Starting work on index: C:\Users\elio\AppData\Roaming\Blender Foundation\Blender\3.5\datafiles\Generator AI\BL_proxy\tmpfar3ea_c.mp4\interp_free_run.blen_tc
Starting work on index: C:\Users\elio\AppData\Roaming\Blender Foundation\Blender\3.5\datafiles\Generator AI\BL_proxy\tmpfar3ea_c.mp4\record_run_no_gaps.blen_tc

**Comment by tin2tin** [comment]
That is only information about proxies are being build. If you give me information, so I can try to reproduce it myself, I might be able to help you solve this.

**Comment by eliecer696** [comment]
that is the only thing that shows up on the console what other information do you need?

**Comment by tin2tin** [comment]
Ex. what is your OS? Blender version? GFX card? VRAM? What model you're using? Did everything install okay? Was the file generated correctly(does it exist)? Anything you think could help me narrow it down, bc I do not get a Blender crash here when proxies have been rendered.

**Comment by eliecer696** [comment]
i found the problem is when i delete a video that was generated from the video track inside the blender editor when i generate another video it will close

**Comment by tin2tin** [comment]
Does that happen with a specific file, or is it all files?

**Comment by tin2tin** [comment]
As it's very likely a bug in Blender, I'll close the report.
