### ISSUE TITLE
potat1: Cannot load "...\vae" because the following keys are missing

### ISSUE THREAD

**Issue by knekke** [tin2tin/Generative_AI#21]
Hi,
I have seen you are already investigating in this:
https://huggingface.co/camenduru/potat1/discussions/2

I'm just linking it here, so it's easier for others to find.

cheers and thanks for the work!

**Comment by tin2tin** [comment]
You'll need Diffusers 0.17beta for that error to go away. If you remove all dependencies(button in the add-on properties), and then install all dependencies, the 0.17beta will be installed instead.

**Comment by knekke** [comment]
That did the trick. Thanks!
