### ISSUE TITLE
torch - the specified module could not be found

### ISSUE THREAD

**Issue by delray** [tin2tin/Generative_AI#22]
I'm close here to getting this going...I mistakenly used an older 3.0 version of blender and got the 'temp override' error and I see I need to be on 3.5

so I installed it fresh, installed the add-on, but now when I try and install the dependencies I get : 
Python: Traceback (most recent call last):
```
  File "C:\Users\mb\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Generative_AI-main\__init__.py", line 500, in execute
    install_modules(self)
  File "C:\Users\mb\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Generative_AI-main\__init__.py", line 259, in install_modules
    exec("import torch")
  File "<string>", line 1, in <module>
  File "C:\Users\mb\AppData\Roaming\Python\Python310\site-packages\torch\__init__.py", line 133, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\mb\AppData\Roaming\Python\Python310\site-packages\torch\lib\cudnn_adv_infer64_8.dll" or one of its dependencies.
```
Do I need to install torch manually ? typically I use it in a conda env, but Im not all the familiar with Blender.
thx!

**Comment by tin2tin** [comment]
Running Blender as admin, try running the "Install Dependencies" one more time and take note if the installation of it fails. If it fails(do you have git installed?), try using the Blender Pip add-on mentioned in the installation instructions to install Torch.

**Comment by tin2tin** [comment]
If there are problems with installing torch, with Blender closed, go to the side package folder: C:\Users\YOUR_USER_NAME\AppData\Roaming\Python\Python310\site-packages and delete every folder called something with torch, and then restart Blender, go to tha add-on properties and try to "Install dependencies".

**Comment by delray** [comment]
Ah ha, great, deleting the torch folder + reinstalling dependencies did it. thanks for your help...now the fun begins ;)

**Comment by tin2tin** [comment]
Cool. I wonder why it didn't work automatically, but pip seems pretty glitchy. 
If you do something cool or find interesting ways to generate stuff then you can share it here in this thread for the add-on: https://blenderartists.org/t/generative-ai-add-on-text-to-video-image-and-audio/1456915
