### ISSUE TITLE
I get bizarre abstract nonsense after the first video render.

### ISSUE THREAD

**Issue by NOSALIS** [tin2tin/Generative_AI#23]
![2023-06-13 20_04_44-Blender](https://github.com/tin2tin/Generative_AI/assets/89745990/61662430-ed8c-49cc-bff2-61580ee04349)

First render comes out "normal"/has recognizable features.

All video results after that are a stream of strange geometric forms.

Also, the resolution doesn't match the "Floyd" resolution, which is the video mode I am using.

**Comment by tin2tin** [comment]
Yes, there's at lot of tweaking(trail&error) necessary to get good results. 

Everything has an effect on the outcome. As a rule of thumb start with the resolution. In the model card selector you can see the resolution the model was trained on. Start entering that. You can always try to change the resolution when you have something working. Depending on your amount of VRam. Try with frames between 18 and 24(however, the new t2v model needs 48 frames). Quality Steps 25-60. Word Power: 8-17.

I've mostly worked in the Animov model. And these values gave me something useful with this model, but other models may need other values, so you'll have to experiment.

I typically get the lines you see, when the number of frames are set too high.

Btw. if you run out of VRam, you'll need to restart Blender.
