### ISSUE TITLE
How to use with pre-existing python/conda installation and env??

### ISSUE THREAD

**Issue by Ainaemaet** [tin2tin/Generative_AI#26]
Hello, 

Very cool plugin you have here, I especially appreciate the newer Zeroscope implementations and the ability to easily do the gens in Blender. 

All that being said, I really think that the method of installation and the instructions are lacking. So many ppl are getting into AI now and they already have Python environments setup on their computers, having to use things this way seems so much clunkier than how I would usually install using terminal, etc. 

Would it be possible to provide some information on how we could go about using our own custom env's?  Thank you. :)

**Comment by tin2tin** [comment]
Blender comes with a local python module and the python modules needs to be installed in that. I haven't worked with virtual environments, and I'm not planning to. If this is something you think can improve this project, you're welcome to submit a patch.
