### ISSUE TITLE
How to install Triton??

### ISSUE THREAD

**Issue by Ainaemaet** [tin2tin/Generative_AI#27]
Hello, 

I get a "A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'" message whenever I use the plugin to generate something. 

I have Triton installed for other programs (like threestudio, various LLM UI's/Libraries, etc.)  in separate env's but I have absolutely no idea how to get it installed here (or if it provides similar boosts as with other generative AI programs) as the (3 year old) Blender_pip plugin you link doesn't seem to include it. 

It is entirely possible I just don't know what I'm doing as far as using Blender-specific Python, but I would be more than happy to learn if that's the case. 

Thankyou.

**Comment by tin2tin** [comment]
This message is something the Diffusers project needs to disable on Windows since Triton does not support Windows. I've notified the Diffusers project about this.

**Comment by Ainaemaet** [comment]
Just noticing this now, thanks for the response. 

This tool is incredible btw, thank you for putting this here for us to try out. 🙏

**Comment by tin2tin** [comment]
Ref: https://github.com/huggingface/diffusers/issues/3937
