### ISSUE TITLE
Many uninstall errors

### ISSUE THREAD

**Issue by Ainaemaet** [tin2tin/Generative_AI#30]
Hello, 

Trying to uninstall dependencies using the plugin 'uninstall dependencies' button and getting a large amount of errors; sharing them here in the event they can help you debug some of the issues
[Generative-AI(BlenderPlugin)ErrorTrace01.txt](https://github.com/tin2tin/Generative_AI/files/12206267/Generative-AI.BlenderPlugin.ErrorTrace01.txt)
. 

Sending as a text attachment as the trace is too big to post here.

**Comment by tin2tin** [comment]
Yes, using pip as this add-on does, is a messy process, but in the end all of it should be removed. 

Except these:
WARNING: Ignoring invalid distribution -orch (q:\users\username\appdata\roaming\python\python310\site-packages)

This is pip keeping a back-up of the modules. Go that path and remove all folders starting with - (Blender needs to be closed first)

**Comment by Ainaemaet** [comment]
Ok, looking into this now. Thanks for the help - really looking forwards to getting all of this working properly and will gladly post some of what I do with it.

**Comment by tin2tin** [comment]
Yesterday I got the refiner step working for Image: Stable Diffusion XL 1.0. It delivers far the best image quality. It can also be used for batching through a selection of text strips, using the texts as prompts. 

I'm hoping Diffusers soon will have some kind of img2vid and vid2vid solutions, so we can have the SD images batch converted into videos.

**Comment by Ainaemaet** [comment]
Serendipity, I was quite literally just thinking of asking you if you had plans to try to implement both img and vid2vid and seen your post in my email. Afaik Runway is the only service with such an offering atm so I'm waiting with baited breath for an open-source solution. 

Haven't tried SDXL yet, decided to skip 0.9 as I was too busy keeping up with all the other stuff so I'm really happy to hear that. I might try my hand at figuring out that  

Are you planning to add a proper implementation of AnimateDiff as well?

(spent a bit of my free time looking into the blender python setup today, I will try to see if I can come up with something over the next couple weeks for setting everything in a venv as I believe a lot of ml folks are using them).
