### ISSUE TITLE
Possibility to include Animatediff?

### ISSUE THREAD

**Issue by Ainaemaet** [tin2tin/Generative_AI#37]
Hey there, absolutely digging the updates lately!!! The img to vid from strips is great and I've managed to get some interesting results I haven't gotten elsewhere (like keeping the main parts of an image intact, and animating just the background which was a surprise). 

I'm curious if it would be possible for you to include Animatediff pipeline somehow, and if you would be interested in implementing it? 

With animatediff I'm able to use whatever SD models I already have to create some great video, but as with almost every implementation outside of this one, the real work comes in when you have to start combining clips, adding audio, etc. While this project makes it so easy to put things together into something cohesive.

**Comment by tin2tin** [comment]
This project is using the python module Diffusers, and maybe animatediff will be implemented in that. Alternatively, VideoComposer(which also has i2v) has been implemented in Modelscope, which is implemented in Diffusers, but not with VideoComposer yet. In other words, I waiting to see what will make it into Diffusers first.

I'm happy to hear that i2v is actually working for you. I'm on 6 GB VRAM and that only allows for 6 frames at 1024x448(Diffusers implemented it so it'll only work with Zeroscope XL). So, please share t2v clips with me, if you make something with i2v so I can see how it works for you. 

And thank you for the kind words on the ease of use. I happy to hear that it is working for you.

**Comment by Ainaemaet** [comment]
Sounds good, I will try to share something here later tonight. 

Another update so I'm excited to get a moment to get into it again. :)

**Comment by tin2tin** [comment]
Closing, as this seems to be answered.
