### ISSUE TITLE
Can't install Text to Audio

### ISSUE THREAD

**Issue by hansnolte** [tin2tin/Generative_AI#4]
Hi tin2tin,

great project!
Unfortunately, I can't get Text to Audio (AudioLDM and Bark) to work.

`Read prefs: E:\Blender-AI\3.4\config\userpref.blend
Win32 Error# (1413): Ung├╝ltiger Index.
Dependencies needs to be installed in the add-on preferences.
Ensuring: pip
Looking in links: c:\Users\SysAdmin\AppData\Local\Temp\tmptzkktw66
Requirement already satisfied: setuptools in e:\blender-ai\3.4\python\lib\site-packages (63.2.0)
Requirement already satisfied: pip in e:\blender-ai\3.4\python\lib\site-packages (23.1.2)
Requirement already satisfied: pip in e:\blender-ai\3.4\python\lib\site-packages (23.1.2)
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Installing: bark module
Collecting git+https://github.com/suno-ai/bark.git
  Cloning https://github.com/suno-ai/bark.git to c:\users\sysadmin\appdata\local\temp\pip-req-build-o17cl4vy
  ERROR: Error [WinError 2] Das System kann die angegebene Datei nicht finden while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
Traceback (most recent call last):
  File "E:\Blender-AI\3.4\scripts\addons\generative_ai-main\__init__.py", line 113, in import_module
    exec("import " + module)
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'bark'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Blender-AI\3.4\scripts\addons\generative_ai-main\__init__.py", line 304, in execute
    install_modules(self)
  File "E:\Blender-AI\3.4\scripts\addons\generative_ai-main\__init__.py", line 212, in install_modules
    import_module(self, "bark", "git+https://github.com/suno-ai/bark.git")
  File "E:\Blender-AI\3.4\scripts\addons\generative_ai-main\__init__.py", line 121, in import_module
    subprocess.check_call(
  File "E:\Blender-AI\3.4\python\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['E:\\Blender-AI\\3.4\\python\\bin\\python.exe', '-m', 'pip', 'install', 'git+https://github.com/suno-ai/bark.git', '--no-warn-script-location', '--user']' returned non-zero exit status 1.
Info: Installing: bark module.
Error: Python: Traceback (most recent call last):
  File "E:\Blender-AI\3.4\scripts\addons\generative_ai-main\__init__.py", line 113, in import_module
    exec("import " + module)
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'bark'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Blender-AI\3.4\scripts\addons\generative_ai-main\__init__.py", line 304, in execute
    install_modules(self)
  File "E:\Blender-AI\3.4\scripts\addons\generative_ai-main\__init__.py", line 212, in install_modules
    import_module(self, "bark", "git+https://github.com/suno-ai/bark.git")
  File "E:\Blender-AI\3.4\scripts\addons\generative_ai-main\__init__.py", line 121, in import_module
    subprocess.check_call(
  File "E:\Blender-AI\3.4\python\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['E:\\Blender-AI\\3.4\\python\\bin\\python.exe', '-m', 'pip', 'install', 'git+https://github.com/suno-ai/bark.git', '--no-warn-script-location', '--user']' returned non-zero exit status 1.

`
WIN 10 64Bit
Blender 3.4.1
Generative AI - Version 1.1

Bye 
Hans

**Comment by hansnolte** [comment]
Hi tin2tin,

thank you very much for your super fast answer.

First I installed GIT.
Then he got gigabytes of dependencies.

Next error message - **_Numpy is missing._**
So, pip install numpy

Next error - **_Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf ._**
Alright, pip install numpy --upgrade

Opened and closed Blender a few times and now TextToAudio seems to be running.

But I still have an error message.
**_A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'_**
Unfortunately I don't know what optimizations Triton is doing. Are they important or can I leave them out?

So, the complete installation is almost 16GB.
Since I only need TextToAudio, and maybe TextToImage, I'll start cleaning up now.
If you have another tip on which folders I can safely delete, bring it on.

Thank you very much for your help and for the addon.

Greetings
Hans

**Comment by tin2tin** [comment]
Yes, the python pip installation seems glitchy. I spend two weeks getting PyTorch to install the right version which could see the CUDA on my RTX card. 

I think the Triton error is bc the Diffusers module is looking for it, but it is not even available on Windows, so they need to disable that. 

I haven't looked into if anything installed is not needed. Let me know if you find anything. I hope you noticed that you can change the model card in the add-on preferences. If you're into sound generation, the Bark module is quite good, for both voice, sounds and music. 

If you find anything interesting, please share the prompts.

**Comment by tin2tin** [comment]
Added numpy update to the dependencies. Thank you!

**Comment by tin2tin** [comment]
@hansnolte I just noticed that Diffusers added a new AudioLDM s Full v2 model - this has been added to the Generative AI add-on just now. I hope it is better that the previous one.

**Comment by hansnolte** [comment]
Hi tin2tin,

I have updated to the AudioLDM s Full v2 model.
Runs flawlessly.
Thank you very much.

Oddly enough, both AudioLDM versions have almost the same byte count.

The "normal AudioLDM has
1,687,789,400 bytes
and the Full V2 has
1,687,789,559 bytes

I assume that the Full V2 will completely replace the old version.
Then you can delete the folder "models--cvssp--audioldm" to save 1.6GB.

If you're still planning to expand Generative AI, check it out.
https://github.com/gaomingqi/Track-Anything
This would be a dream come true for many Blender users.

Many greetings and thanks again
Hans

**Comment by tin2tin** [comment]
@hansnolte keep me posted if you come up with something cool. I'll close this report, feel free to reopen it or make a new one if you find a bug.

**Comment by tin2tin** [comment]
@hansnolte I made BArk use v2 voices. However bark must be updated manually. It isn't enough to remove the module with pip, you must also locate the bark side-package and remove it manually, before clicking on the Install All Dependencies, again.

**Comment by hansnolte** [comment]
Hi tin2tin,
thank you very much for the note.

I hope I have a little time in the next few days.
Then I will completely reinstall Generative AI again, I think that makes more sense.

Best regards
Hans

**Comment by tin2tin** [comment]
I should properly add some kind of buttons for auto-update and auto-removal of python(and their side packages) and ai-data-sets, though it may not be a good thing to update python modules blindly, bc it can cause incompatibilities.
