### ISSUE TITLE
'Context' object has no attribute 'temp_override'  location: <unknown location>:-1

### ISSUE THREAD

**Issue by k-a-s-o-u** [tin2tin/Generative_AI#5]
Hello, thank you so much for your great Blender add-on, however I've got this error at the first generating on Blender 3.0.0.

<error message>
location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Generative_AI-main\__init__.py", line 601, in execute
    with context.temp_override(window=window, area=area):
AttributeError: 'Context' object has no attribute 'temp_override'

location: <unknown location>:-1
<end message>

Install dependencies has finished but it got this 1 error message.
Error, region type 2 missing in - name:"Sequencer", id:8

Do you have any idea how to fix this?

**Comment by tin2tin** [comment]
Update to Blender 3.5. This context.temp_override function is new in the API.

**Comment by tin2tin** [comment]
Did that solve your problem?

**Comment by tin2tin** [comment]
Thank you so much for getting back to me. You're the first person, I know, who managed to install and use the add-on successfully. Feel free to share your findings or if you do something cool here at github.

**Comment by tin2tin** [comment]
I opened a discussion section here in GitHub, so if you want to share things you do with the add-on, then please do it there. 

As this issue has been solved, I'll close it.
