### ISSUE TITLE
Linux: starting the extension crashes Blender

### ISSUE THREAD

**Issue by kaosbeat** [tin2tin/Generative_AI#8]
Hi,

after smooth install on Linux (ubuntu 23.04) and blender 3.5.1 (snap) and installing a missing package uysing pip as described in the install instructions, blender crashes when converting a text block. The log says:

```
journalctl -f | grep blender
mei 08 10:38:27 kaosfury systemd[2548]: Started snap.blender.blender.34735eb8-3dd3-4d26-84c8-7433fbdab752.scope.
mei 08 10:38:50 kaosfury blender_blender.desktop[457515]: : CommandLine Error: Option 'nvptx-no-f16-math' registered more than once!
mei 08 10:38:50 kaosfury blender_blender.desktop[457515]: LLVM ERROR: inconsistency in registered CommandLine options
mei 08 10:38:51 kaosfury blender_blender.desktop[457488]: Aborted (core dumped)
mei 08 10:38:51 kaosfury systemd[2548]: snap.blender.blender.34735eb8-3dd3-4d26-84c8-7433fbdab752.scope: Consumed 8.328s CPU time.
```

any idea what might be causing this?

**Comment by tin2tin** [comment]
What package was missing? (I can add that to the automatic installation)
I know noting about Linux, and none of the stuff from the log makes any sense to me. 
I'm sorry. Maybe someone else around here can help?
Let me know if you find a way around this.

**Comment by tin2tin** [comment]
any news on this?

**Comment by kaosbeat** [comment]
Hey, still crashing, I looked into it but cannot find anything.
I still want to fix it though we're going to need someone with Linux/python
specifics skills...

I ended up running bark and modelscope locally and both work fine outside
blender...

**Comment by tin2tin** [comment]
Okay. Thank you. Aren't there any other logs or info on what is going wrong? 
Good to know that the modules are working as they should on Linux, so it's either incompatible libs used or something in the actual add-on, which makes Blender crash.

**Comment by tin2tin** [comment]
This problem seems to have been solved: https://github.com/tin2tin/Generative_AI/issues/15
